#!/usr/bin/env python3
"""Hand-declared V2 lifecycle oracles; stdlib only, no JVM/allocator/subprocess.

Run with python3 -B scripts/test-file-lifecycle.py. Fixtures are ordinary small
JSON documents, not exports or observations generated by the implementation.
"""
import copy
from decimal import Decimal
import json
import math
from pathlib import Path
import sys
import unittest
from unittest import mock

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _network_audit import decode_json
from _file_lifecycle_audit import Invalid, inspect_path, verify_document

INT_MAX, LONG_MAX = 2147483647, 9223372036854775807


def fid(name="data", scope=0):
    return dict(workflowInputIndex=scope, name=name)


def loc(vm=None):
    return dict(kind="SOURCE" if vm is None else "VM", vmId=vm,
                sourceId="source" if vm is None else None)


def file(name, size, producer=None, scope=0):
    return dict(fileId=fid(name, scope), bytes=size, producerTaskId=producer)


def task(ident, parents=(), inputs=(), outputs=(), scope=0):
    return dict(taskId=ident, workflowInputIndex=scope, parents=list(parents),
                inputs=[dict(fileId=fid(name, scope), referenceCount=count) for name, count in inputs],
                outputs=[fid(name, scope) for name in outputs])


def endpoints(vms=((1, 10), (2, 20), (3, 50))):
    return dict(locations=[loc(vm) for vm, _ in vms] + [loc()],
                resources=[dict(key="VM:" + str(vm), capacityBytesPerSecond=rate) for vm, rate in vms],
                vmHostAssignments=[], topology=None)


def e(kind, now, **payload):
    return dict(sequence=0, type=kind, observedTime=now, payload=payload)


def request(job, tid, vm, now):
    return e("JOB_INPUT_REQUESTED", now, jobId=job, taskIds=[tid], destinationVmId=vm)


def ready(job, now):
    return e("JOB_DATA_READY", now, jobId=job)


def cpu(job, vm, now):
    return e("JOB_CPU_STARTED", now, jobId=job, vmId=vm)


def finish(job, tid, vm, now, success=True):
    return e("TASK_FINISHED", now, jobId=job, taskId=tid, vmId=vm, success=success)


def seed(name, scope=0):
    return e("EXTERNAL_SEEDED", 0, fileId=fid(name, scope), location=loc())


def replica(name, holder, visible, acquisition, producer=None, attempt=None,
            origin_holder=None, origin_at=0, copied_from=None, ordinal=None, scope=0):
    return dict(fileId=fid(name, scope), location=loc(holder), visibleAt=visible, acquisition=acquisition,
                origin=dict(producerTaskId=producer, jobAttemptId=attempt,
                            location=loc(origin_holder), observedAt=origin_at),
                copiedFrom=copied_from, copyOrdinal=ordinal)


def admit(ordinal, name, source, vm, size, path, rate, seconds, now, scope=0):
    return e("COPY_ADMITTED", now, copyOrdinal=ordinal, fileId=fid(name, scope), bytes=size,
             sourceReplica=source, destinationVmId=vm, resources=path,
             standaloneRate=rate, isolatedSeconds=seconds)


def resolve(job, name, resolution, source, now, ordinal=None, count=1, scope=0):
    return e("INPUT_RESOLVED", now, jobId=job, fileId=fid(name, scope), referenceCount=count,
             resolution=resolution, copyOrdinal=ordinal, source=loc(source))


def settle(ordinal, effective, observed, residual=0):
    return e("COPY_SETTLED", observed, copyOrdinal=ordinal,
             effectiveTime=effective, remainingAfterService=residual)


def seal(doc, through=None):
    """Re-sequence and recount after mutation: bookkeeping cannot hide a semantic deletion."""
    for sequence, event in enumerate(doc["events"], 1):
        event["sequence"] = sequence
    doc["capture"]["retainedRecords"] = len(doc["events"])
    doc["capture"]["observedThrough"] = (doc["events"][-1]["observedTime"] if doc["events"] else 0) if through is None else through
    return doc


def document(tasks=(), files=(), events=(), fabric=None, isolated=False):
    doc = dict(schema="workflowsim-file-lifecycle-v2",
               modelKind="COHERENT_FILE_DATAFLOW_NO_CONTENTION_V2" if isolated else "COHERENT_FILE_DATAFLOW_V2",
               recording=dict(mode="FILE_LIFECYCLE_V2", maxTraceRecords=1000),
               certificateScope="FILE_LIFECYCLE_NOT_FLUID_SERVICE_ACCOUNTING_V2",
               policies=dict(fileIdentity="SCOPED_RESOLVED_WRITE_ONCE_FILES_V2",
                             release="DEPENDENCY_READY_AT_OBSERVATION_V2",
                             visibility="PER_FILE_SETTLEMENT_OBSERVATION_V2",
                             selection="VISIBLE_LOCAL_OR_MAX_ISOLATED_RATE_STABLE_LOCATION_V2",
                             sourceAccess="UNBOUNDED_OFF_FABRIC_SOURCE_INPUT_V2",
                             sharing="ISOLATED_PATH_BOTTLENECK" if isolated else "SHARED_MAX_MIN"),
               capture=dict(status="COMPLETE", observedThrough=0, retainedRecords=0, droppedRecords=0),
               filePlan=dict(contractVersion="SCOPED_RESOLVED_WRITE_ONCE_FILES_V2", tasks=list(tasks), files=list(files)),
               fabric=endpoints() if fabric is None else fabric, events=list(events))
    return seal(doc)


def publication():
    """100 bytes published at VM1, copied at 10 B/s; effective12, visible15."""
    original = replica("data", 1, 1, "TASK_OUTPUT", 10, 100, 1, 1)
    return document([task(10, outputs=["data"]), task(11, parents=[10], inputs=[("data", 3)])],
                    [file("data", 100, 10)],
                    [request(100, 10, 1, 0), ready(100, 0), cpu(100, 1, 0), finish(100, 10, 1, 1),
                     request(101, 11, 2, 2), admit(1, "data", original, 2, 100, ["VM:1", "VM:2"], 10, 10, 2),
                     resolve(101, "data", "NEW_COPY", 1, 2, 1, 3), settle(1, 12, 15), ready(101, 15),
                     cpu(101, 2, 15), finish(101, 11, 2, 16)])


def fanin():
    """Fast file visible independently; same-target join; VM2 cache is a faster holder."""
    fast = replica("fast", 1, 1, "TASK_OUTPUT", 0, 10, 1, 1)
    slow = replica("slow", 1, 1, "TASK_OUTPUT", 0, 10, 1, 1)
    cache = replica("fast", 2, 4, "COPY_SETTLEMENT", 0, 10, 1, 1, loc(1), 1)
    return document([task(0, outputs=["fast", "slow"]),
                     task(1, parents=[0], inputs=[("fast", 2), ("slow", 1)]),
                     task(2, parents=[0], inputs=[("fast", 1)]),
                     task(3, parents=[0], inputs=[("fast", 1)])],
                    [file("fast", 10, 0), file("slow", 100, 0)],
                    [request(10, 0, 1, 0), ready(10, 0), cpu(10, 1, 0), finish(10, 0, 1, 1),
                     request(11, 1, 2, 1), admit(1, "fast", fast, 2, 10, ["VM:1", "VM:2"], 10, 1, 1),
                     resolve(11, "fast", "NEW_COPY", 1, 1, 1, 2),
                     admit(2, "slow", slow, 2, 100, ["VM:1", "VM:2"], 10, 10, 1),
                     resolve(11, "slow", "NEW_COPY", 1, 1, 2),
                     request(12, 2, 2, 2), resolve(12, "fast", "JOIN_EXISTING", 1, 2, 1),
                     settle(1, 3, 4), ready(12, 4), cpu(12, 2, 4), finish(12, 2, 2, 5),
                     request(13, 3, 3, 5), admit(3, "fast", cache, 3, 10, ["VM:2", "VM:3"], 50, .2, 5),
                     resolve(13, "fast", "NEW_COPY", 2, 5, 3), settle(3, 5.2, 6), ready(13, 6),
                     cpu(13, 3, 6), finish(13, 3, 3, 7), settle(2, 12, 15), ready(11, 15),
                     cpu(11, 2, 15), finish(11, 1, 2, 16)],
                    endpoints(((1, 10), (2, 100), (3, 50))))


def failure_retry():
    external = replica("external", None, 0, "EXTERNAL_SEED")
    output = replica("out", 1, 15, "TASK_OUTPUT", 0, 11, 1, 15)
    return document([task(0, inputs=[("external", 2)], outputs=["out"]),
                     task(1, parents=[0], inputs=[("out", 1)]), task(2, inputs=[("external", 1)])],
                    [file("external", 100), file("out", 40, 0)],
                    [seed("external"), request(10, 0, 1, 0),
                     admit(1, "external", external, 1, 100, ["VM:1"], 10, 10, 0),
                     resolve(10, "external", "NEW_COPY", None, 0, 1, 2),
                     request(20, 2, 1, 1), resolve(20, "external", "JOIN_EXISTING", None, 1, 1),
                     settle(1, 10, 12), ready(10, 12), ready(20, 12), cpu(10, 1, 12), cpu(20, 1, 12),
                     finish(10, 0, 1, 13, False), finish(20, 2, 1, 13),
                     request(11, 0, 1, 14), resolve(11, "external", "LOCAL", 1, 14, count=2),
                     ready(11, 14), cpu(11, 1, 14), finish(11, 0, 1, 15),
                     request(12, 1, 2, 15), admit(2, "out", output, 2, 40, ["VM:1", "VM:2"], 10, 4, 15),
                     resolve(12, "out", "NEW_COPY", 1, 15, 2), settle(2, 19, 20), ready(12, 20),
                     cpu(12, 2, 20), finish(12, 1, 2, 21)])


def zeros():
    return document([task(0, inputs=[("zero", 1)]), task(1, inputs=[("zero", 1)]), task(2, inputs=[("zero", 1)])],
                    [file("zero", 0)],
                    [seed("zero"), request(0, 0, 9, 1), resolve(0, "zero", "ZERO", None, 1),
                     ready(0, 1), cpu(0, 9, 1), finish(0, 0, 9, 1, False),
                     request(1, 1, 10, 2), resolve(1, "zero", "ZERO", 9, 2),
                     ready(1, 2), cpu(1, 10, 2), finish(1, 1, 10, 2),
                     request(2, 2, 11, 3), resolve(2, "zero", "ZERO", 9, 3),
                     ready(2, 3), cpu(2, 11, 3), finish(2, 2, 11, 3),
                     request(3, 0, 9, 4), resolve(3, "zero", "LOCAL", 9, 4),
                     ready(3, 4), cpu(3, 9, 4), finish(3, 0, 9, 4)],
                    endpoints(((9, 1), (10, 100), (11, 100))))


def fat_fabric(k=2, cores=1, placements=((10, 0, 0), (20, 1, 0))):
    """Declare physical inventory; the expected paths below are independent literals."""
    fabric = endpoints(((1, 50), (2, 40), (3, 30)))
    fabric["vmHostAssignments"] = [dict(vmId=1, hostId=10), dict(vmId=2, hostId=20), dict(vmId=3, hostId=10)]
    fabric["topology"] = dict(kind="FAT_TREE", k=k, coreSwitchCount=cores, linkBandwidthBytesPerSecond=10,
                              hostPlacements=[dict(hostId=h, pod=p, edge=e) for h, p, e in placements])
    half = k // 2
    pairs = [("ACC:" + str(h), f"EDGE:{p}:{e}") for h, p, e in placements]
    pairs += [(f"EDGE:{p}:{e}", f"AGG:{p}:{a}") for p in range(k) for e in range(half) for a in range(half)]
    pairs += [(f"AGG:{p}:{c // half}", "CORE:" + str(c)) for p in range(k) for c in range(cores)]
    for a, b in pairs:
        fabric["resources"].extend([dict(key=f"LINK:{a}->{b}", capacityBytesPerSecond=10),
                                    dict(key=f"LINK:{b}->{a}", capacityBytesPerSecond=10)])
    return fabric


CROSS_PATH = ["VM:1", "LINK:ACC:10->EDGE:0:0", "LINK:EDGE:0:0->AGG:0:0",
              "LINK:AGG:0:0->CORE:0", "LINK:CORE:0->AGG:1:0",
              "LINK:AGG:1:0->EDGE:1:0", "LINK:EDGE:1:0->ACC:20", "VM:2"]
REVERSE_PATH = ["VM:2", "LINK:ACC:20->EDGE:1:0", "LINK:EDGE:1:0->AGG:1:0",
                "LINK:AGG:1:0->CORE:0", "LINK:CORE:0->AGG:0:0",
                "LINK:AGG:0:0->EDGE:0:0", "LINK:EDGE:0:0->ACC:10", "VM:1"]


def fat_document():
    doc = publication()
    doc["fabric"] = fat_fabric()
    doc["events"][5]["payload"]["resources"] = list(CROSS_PATH)
    return doc


def changed(doc, path, value):
    result = copy.deepcopy(doc)
    target = result
    for key in path[:-1]:
        target = target[key]
    target[path[-1]] = value
    return result


def prefix(doc, count, through=None):
    result = copy.deepcopy(doc)
    result["events"] = result["events"][:count]
    return seal(result, through)


def audit(doc):
    return verify_document(decode_json(json.dumps(doc, ensure_ascii=True, allow_nan=False)))


class LifecycleOracles(unittest.TestCase):
    def bad(self, doc):
        with self.assertRaises(Invalid):
            verify_document(doc)

    def test_publication_copy_and_late_visibility(self):
        report = audit(publication())
        self.assertEqual("VALID_COMPLETE", report["status"])
        self.assertTrue(report["completeCaptureCertified"])
        self.assertFalse(report["fluidServiceAccountingCertified"])
        self.assertFalse(report["contextualRunChecked"])
        self.assertEqual((1, 1, 0, 0), tuple(report[key] for key in
                                          ("admissionCount", "settlementCount", "activeCopyCount", "waitingJobCount")))
        self.assertEqual(300, report["facts"]["jobs"][1]["requiredReferenceBytes"])
        self.assertEqual(15, report["facts"]["jobs"][1]["dataReadyAt"])
        target = report["facts"]["replicas"][1]
        self.assertEqual((15, 1, 1), (target["visibleAt"], target["origin"]["observedAt"], target["copyOrdinal"]))
        self.assertEqual(loc(1), target["copiedFrom"])
        self.assertTrue(report["lifecycleQuiescent"])

    def test_both_models_and_empty_are_complete_not_disabled(self):
        for isolated in (False, True):
            doc = document(isolated=isolated)
            result = audit(doc)
            self.assertEqual("VALID_COMPLETE", result["status"])
            self.assertEqual(0, result["admissionCount"])
        doc = publication()
        doc["modelKind"] = "COHERENT_FILE_DATAFLOW_NO_CONTENTION_V2"
        doc["policies"]["sharing"] = "ISOLATED_PATH_BOTTLENECK"
        self.assertEqual(1, audit(doc)["settlementCount"])

    def test_complete_operation_prefix_can_wait_run_or_be_ready(self):
        waiting = audit(prefix(publication(), 7, 2))
        self.assertEqual((1, 1, 1), (waiting["activeCopyCount"], waiting["waitingJobCount"], waiting["unfinishedJobCount"]))
        self.assertFalse(waiting["lifecycleQuiescent"])
        ready_report = audit(prefix(publication(), 9))
        self.assertEqual(1, ready_report["readyNotStartedJobCount"])
        running = audit(prefix(publication(), 10))
        self.assertEqual(1, running["runningJobCount"])
        # The standalone scope cannot authenticate deletion of a whole valid
        # suffix or join this prefix to an enclosing completed-run manifest.
        self.assertEqual("VALID_COMPLETE", waiting["status"])

    def test_fanin_independent_publication_join_and_cache_origin(self):
        full = fanin()
        early = audit(prefix(full, 13))
        self.assertEqual(1, early["waitingJobCount"])
        self.assertEqual(1, early["activeCopyCount"])
        self.assertEqual(1, early["readyNotStartedJobCount"])
        report = audit(full)
        copy3 = report["facts"]["copies"][2]
        self.assertEqual(["VM:2", "VM:3"], copy3["resources"])
        self.assertEqual(loc(2), copy3["sourceReplica"]["location"])
        self.assertEqual(loc(1), copy3["sourceReplica"]["origin"]["location"])
        self.assertEqual((4, 1), (copy3["sourceReplica"]["visibleAt"], copy3["sourceReplica"]["copyOrdinal"]))
        self.assertEqual(3, report["admissionCount"])
        self.assertEqual("JOIN_EXISTING", report["facts"]["jobs"][2]["inputs"][0]["resolution"])

    def test_positive_source_tie_uses_numeric_vm_order_not_age_or_text(self):
        chosen = replica("data", 2, 2, "TASK_OUTPUT", 0, 20, 2, 2)
        doc = document([task(0, outputs=["data"]), task(1, parents=[0], inputs=[("data", 1)])],
                       [file("data", 10, 0)],
                       [request(10, 0, 10, 0), ready(10, 0), cpu(10, 10, 0), finish(10, 0, 10, 1),
                        request(20, 0, 2, 1), ready(20, 1), cpu(20, 2, 1), finish(20, 0, 2, 2),
                        request(30, 1, 99, 2), admit(1, "data", chosen, 99, 10, ["VM:2", "VM:99"], 10, 1, 2),
                        resolve(30, "data", "NEW_COPY", 2, 2, 1), settle(1, 3, 4), ready(30, 4),
                        cpu(30, 99, 4), finish(30, 1, 99, 5)], endpoints(((2, 10), (10, 10), (99, 20))))
        self.assertEqual(loc(2), audit(doc)["facts"]["copies"][0]["sourceReplica"]["location"])
        doc["events"][9]["payload"].update(sourceReplica=replica("data", 10, 1, "TASK_OUTPUT", 0, 10, 10, 1),
                                          resources=["VM:10", "VM:99"])
        doc["events"][10]["payload"]["source"] = loc(10)
        self.bad(doc)

    def test_selection_uses_max_rate_not_original_producer(self):
        doc = fanin()
        p = doc["events"][16]["payload"]
        p.update(sourceReplica=replica("fast", 1, 1, "TASK_OUTPUT", 0, 10, 1, 1),
                 resources=["VM:1", "VM:3"], standaloneRate=10, isolatedSeconds=1)
        doc["events"][17]["payload"]["source"] = loc(1)
        self.bad(doc)

    def test_join_keeps_frozen_source_even_after_a_better_publication(self):
        doc = prefix(fanin(), 11)
        doc["filePlan"]["tasks"].append(task(4, parents=[0], inputs=[("fast", 1)]))
        doc["events"].extend([request(20, 0, 3, 2.5), ready(20, 2.5), cpu(20, 3, 2.5), finish(20, 0, 3, 2.5),
                              request(14, 4, 2, 3), resolve(14, "fast", "JOIN_EXISTING", 1, 3, 1)])
        report = audit(seal(doc))
        self.assertEqual((2, 3), (report["activeCopyCount"], report["waitingJobCount"]))
        doc["events"][-1]["payload"]["source"] = loc(3)
        self.bad(doc)

    def test_failure_retry_preserves_cache_and_only_success_publishes(self):
        doc = failure_retry()
        failed = audit(prefix(doc, 13))
        self.assertFalse(any(r["fileId"] == fid("out") for r in failed["facts"]["replicas"]))
        report = audit(doc)
        jobs = {j["jobId"]: j for j in report["facts"]["jobs"]}
        self.assertFalse(jobs[10]["success"])
        self.assertEqual("LOCAL", jobs[11]["inputs"][0]["resolution"])
        self.assertEqual(2, report["admissionCount"])
        out = next(r for r in report["facts"]["replicas"] if r["fileId"] == fid("out"))
        self.assertEqual((11, 15), (out["origin"]["jobAttemptId"], out["origin"]["observedAt"]))
        wrong = changed(doc, ("events", 19, "payload", "sourceReplica", "origin", "jobAttemptId"), 10)
        self.bad(wrong)
        too_early = prefix(doc, 13)
        too_early["events"].append(request(12, 1, 2, 13))
        self.bad(seal(too_early))

    def test_first_target_publication_survives_later_copy_settlement(self):
        doc = prefix(publication(), 7)
        doc["events"].extend([request(102, 10, 2, 3), ready(102, 3), cpu(102, 2, 3), finish(102, 10, 2, 4),
                              ready(101, 4), settle(1, 12, 15), cpu(101, 2, 15), finish(101, 11, 2, 16)])
        result = audit(seal(doc))
        target = next(r for r in result["facts"]["replicas"] if r["location"] == loc(2))
        self.assertEqual(("TASK_OUTPUT", 4, 102, None),
                         (target["acquisition"], target["visibleAt"], target["origin"]["jobAttemptId"], target["copyOrdinal"]))
        self.assertEqual(4, result["facts"]["jobs"][1]["dataReadyAt"])

    def test_repeated_success_does_not_replace_first_origin(self):
        doc = publication()
        doc["events"].extend([request(102, 10, 1, 17), ready(102, 17), cpu(102, 1, 17), finish(102, 10, 1, 18)])
        source = audit(seal(doc))["facts"]["replicas"][0]
        self.assertEqual((1, 100), (source["visibleAt"], source["origin"]["jobAttemptId"]))

    def test_zero_source_order_local_priority_and_no_network(self):
        report = audit(zeros())
        self.assertEqual(0, report["admissionCount"])
        self.assertEqual(4, report["replicaCount"])
        self.assertEqual("LOCAL", report["facts"]["jobs"][-1]["inputs"][0]["resolution"])
        z10 = next(r for r in report["facts"]["replicas"] if r["location"] == loc(10))
        self.assertEqual(("ZERO_BYTE_REFERENCE", None, loc(9)),
                         (z10["acquisition"], z10["copyOrdinal"], z10["copiedFrom"]))
        for row, source in ((7, None), (12, 10)):
            with self.subTest(row=row):
                self.bad(changed(zeros(), ("events", row, "payload", "source"), loc(source)))
        self.bad(changed(zeros(), ("events", 17, "payload", "resolution"), "ZERO"))

    def test_same_exact_name_in_distinct_workflows_never_aliases(self):
        name = "input[7]/colon:name/unchanged"
        external = replica(name, None, 0, "EXTERNAL_SEED", scope=1)
        doc = document([task(0, outputs=[name]), task(1, inputs=[(name, 1)], scope=1)],
                       [file(name, 10, 0), file(name, 20, scope=1)],
                       [seed(name, 1), request(0, 0, 1, 1), ready(0, 1), cpu(0, 1, 1), finish(0, 0, 1, 2),
                        request(1, 1, 2, 3), admit(1, name, external, 2, 20, ["VM:2"], 20, 1, 3, scope=1),
                        resolve(1, name, "NEW_COPY", None, 3, 1, scope=1), settle(1, 4, 5), ready(1, 5),
                        cpu(1, 2, 5), finish(1, 1, 2, 6)])
        result = audit(doc)
        self.assertEqual(2, result["fileCount"])
        self.assertEqual({name}, {r["fileId"]["name"] for r in result["facts"]["replicas"]})
        self.bad(changed(doc, ("events", 6, "payload", "fileId", "workflowInputIndex"), 0))

    def test_ancestor_not_necessarily_direct_parent(self):
        doc = document([task(0, outputs=["x"]), task(1, parents=[0]), task(2, parents=[1], inputs=[("x", 1)])],
                       [file("x", 1, 0)])
        self.assertEqual(3, audit(doc)["taskCount"])
        self.bad(changed(doc, ("filePlan", "tasks", 1, "parents"), []))
        self.bad(changed(doc, ("filePlan", "tasks", 0, "parents"), [2]))
        self.bad(changed(doc, ("filePlan", "tasks", 1, "workflowInputIndex"), 1))

    def test_declaration_array_order_is_not_semantic_and_utf16_names_are_exact(self):
        doc = publication()
        doc["filePlan"]["tasks"].reverse()
        self.assertEqual(2, audit(doc)["taskCount"])
        # Java UTF-16 ordering places the surrogate pair for U+10000 before U+E000.
        names = ["\U00010000", "\ue000"]
        doc = document([task(0, inputs=[(names[1], 1), (names[0], 1)])],
                       [file(names[1], 0), file(names[0], 0)],
                       [seed(names[0]), seed(names[1]), request(0, 0, 1, 0),
                        resolve(0, names[0], "ZERO", None, 0), resolve(0, names[1], "ZERO", None, 0), ready(0, 0)])
        self.assertEqual(4, audit(doc)["replicaCount"])

    def test_root_capture_and_strict_key_mutations(self):
        base = publication()
        bad_values = [(("schema",), "workflowsim-network-ledger-v1"),
                      (("modelKind",), "DISABLED"), (("certificateScope",), "FLUID_SERVICE"),
                      (("recording", "mode"), "OFF"), (("recording", "maxTraceRecords"), 0),
                      (("recording", "maxTraceRecords"), INT_MAX + 1),
                      (("policies", "sharing"), "ISOLATED_PATH_BOTTLENECK"),
                      (("policies", "sourceAccess"), "BOUNDED"),
                      (("capture", "status"), "TRUNCATED"), (("capture", "status"), "DISABLED"),
                      (("capture", "droppedRecords"), 1), (("capture", "retainedRecords"), 999),
                      (("capture", "observedThrough"), 15), (("events", 0, "type"), "READY")]
        for path, value in bad_values:
            with self.subTest(path=path, value=value):
                self.bad(changed(base, path, value))
        for path in ((), ("recording",), ("capture",), ("filePlan",), ("filePlan", "tasks", 0),
                     ("fabric",), ("events", 0), ("events", 0, "payload")):
            doc = copy.deepcopy(base)
            obj = doc
            for key in path:
                obj = obj[key]
            obj["unknown"] = None
            with self.subTest(extra=path):
                self.bad(doc)
        self.bad(changed(base, ("recording", "maxTraceRecords"), len(base["events"]) - 1))
        doc = changed(base, ("recording", "maxTraceRecords"), len(base["events"]))
        self.assertTrue(audit(doc)["completeCaptureCertified"])

    def test_file_plan_unknown_duplicate_in_place_and_scope_mutations(self):
        base = publication()
        mutations = [(("filePlan", "files", 0, "producerTaskId"), 99),
                     (("filePlan", "files", 0, "producerTaskId"), None),
                     (("filePlan", "files", 0, "bytes"), -1),
                     (("filePlan", "files", 0, "fileId", "name"), ""),
                     (("filePlan", "tasks", 1, "parents"), [10, 10]),
                     (("filePlan", "tasks", 1, "parents"), [99]),
                     (("filePlan", "tasks", 1, "inputs", 0, "referenceCount"), 0),
                     (("filePlan", "tasks", 1, "inputs", 0, "fileId", "workflowInputIndex"), 1),
                     (("filePlan", "tasks", 0, "outputs"), []),
                     (("filePlan", "tasks", 0, "inputs"), [dict(fileId=fid(), referenceCount=1)])]
        for path, value in mutations:
            with self.subTest(path=path):
                self.bad(changed(base, path, value))
        for path in (("filePlan", "tasks"), ("filePlan", "files"),
                     ("filePlan", "tasks", 1, "inputs"), ("filePlan", "tasks", 0, "outputs")):
            doc = copy.deepcopy(base)
            array = doc
            for key in path:
                array = array[key]
            array.append(copy.deepcopy(array[0]))
            self.bad(doc)
        self.bad(document(files=[file("orphan", 0)]))

    def test_exact_large_integer_and_decimal_counter_contract(self):
        # No request: a single long reference count is data, not a demand to
        # allocate LONG_MAX FileItems. The accepted answer has only one seed.
        base = document([task(INT_MAX, inputs=[("external", LONG_MAX)])], [file("external", 0)], [seed("external")])
        self.assertEqual(1, audit(base)["retainedRecords"])
        for path, token in [(("filePlan", "tasks", 0, "taskId"), "2147483647.0000000001"),
                            (("filePlan", "tasks", 0, "inputs", 0, "referenceCount"), "9223372036854775807.1"),
                            (("filePlan", "tasks", 0, "inputs", 0, "referenceCount"), "9223372036854775808"),
                            (("capture", "retainedRecords"), "1.0000000000000000000001"),
                            (("events", 0, "sequence"), "1.0000000000000000000001"),
                            (("recording", "maxTraceRecords"), "2147483647.0000000001")]:
            doc = changed(base, path, "NUMERIC_SENTINEL")
            parsed = decode_json(json.dumps(doc).replace('"NUMERIC_SENTINEL"', token))
            with self.subTest(token=token, path=path):
                self.bad(parsed)
        requested = copy.deepcopy(base)
        requested["events"].append(request(0, INT_MAX, 1, 0))
        self.bad(seal(requested))
        # Exact integral exponent/decimal lexemes remain valid numbers.
        base["filePlan"]["tasks"][0]["inputs"][0]["referenceCount"] = "NUMERIC_SENTINEL"
        self.assertEqual(1, verify_document(decode_json(json.dumps(base).replace('"NUMERIC_SENTINEL"', "9.223372036854775807e18")))["seedCount"])

    def test_nested_ids_and_ordinals_never_round_fractional_decimals_to_integers(self):
        base = publication()
        for path in (("events", 0, "payload", "jobId"),
                     ("events", 0, "payload", "taskIds", 0),
                     ("events", 0, "payload", "destinationVmId"),
                     ("events", 5, "payload", "copyOrdinal"),
                     ("events", 5, "payload", "sourceReplica", "origin", "jobAttemptId"),
                     ("events", 5, "payload", "sourceReplica", "origin", "producerTaskId"),
                     ("fabric", "locations", 0, "vmId"),
                     ("filePlan", "tasks", 1, "parents", 0)):
            original = base
            for key in path:
                original = original[key]
            token = str(original) + ".0000000000000000000000000001"
            doc = changed(base, path, "NUMERIC_SENTINEL")
            with self.subTest(path=path):
                self.bad(decode_json(json.dumps(doc).replace('\"NUMERIC_SENTINEL\"', token)))

    def test_boolean_string_nonfinite_and_underflow_are_not_numbers(self):
        for value in (True, "100", None, float("nan"), float("inf"), Decimal("1e-999")):
            with self.subTest(value=value):
                self.bad(changed(publication(), ("filePlan", "files", 0, "bytes"), value))
        for path in (("events", 0, "payload", "jobId"), ("capture", "retainedRecords"),
                     ("events", 5, "payload", "copyOrdinal")):
            self.bad(changed(publication(), path, True))
        for text in ('{"x":1,"x":2}', '{"x":NaN}', '{"x":Infinity}', '{"x":1e99999}'):
            with self.subTest(text=text), self.assertRaises(ValueError):
                decode_json(text)

    def test_atomic_request_and_due_ready_cannot_be_missing_at_end(self):
        for count in (1, 5, 6, 8):
            with self.subTest(count=count):
                self.bad(prefix(publication(), count))
        self.bad(prefix(fanin(), 7))       # One of two normalized inputs omitted.
        self.bad(prefix(failure_retry(), 8))  # Second waiter readiness omitted.

    def test_recounted_deletions_remain_invalid(self):
        for index in (0, 1, 2, 3, 4, 5, 6, 7, 8, 9):
            doc = publication()
            del doc["events"][index]
            with self.subTest(deleted=index):
                self.bad(seal(doc))
        doc = failure_retry()
        del doc["events"][0]
        self.bad(seal(doc))

    def test_duplicate_settlement_and_task_outcome_are_not_idempotent_events(self):
        for index in (3, 6, 7, 8, 9, 10):
            doc = publication()
            doc["events"].insert(index + 1, copy.deepcopy(doc["events"][index]))
            with self.subTest(duplicate=index):
                self.bad(seal(doc))

    def test_same_timestamp_sequence_is_causality_not_just_clock(self):
        doc = publication()
        doc["events"][8:10] = list(reversed(doc["events"][8:10]))  # CPU before required ready.
        self.bad(seal(doc))
        doc = failure_retry()
        doc["events"][7:9] = list(reversed(doc["events"][7:9]))   # Waiter insertion order.
        self.bad(seal(doc))
        self.bad(changed(publication(), ("events", 6, "observedTime"), 3))
        self.bad(changed(publication(), ("events", 8, "observedTime"), 16))
        self.bad(changed(publication(), ("events", 4, "observedTime"), .5))

    def test_event_membership_fixed_vm_and_resolution_fail_closed(self):
        base = publication()
        mutations = [(("events", 0, "payload", "taskIds"), []),
                     (("events", 0, "payload", "taskIds"), [10, 11]),
                     (("events", 0, "payload", "taskIds"), [99]),
                     (("events", 4, "payload", "jobId"), 100),
                     (("events", 6, "payload", "jobId"), 100),
                     (("events", 6, "payload", "referenceCount"), 1),
                     (("events", 6, "payload", "copyOrdinal"), None),
                     (("events", 6, "payload", "resolution"), "JOIN_EXISTING"),
                     (("events", 6, "payload", "resolution"), "LOCAL"),
                     (("events", 6, "payload", "resolution"), "ZERO"),
                     (("events", 9, "payload", "vmId"), 1),
                     (("events", 10, "payload", "vmId"), 1),
                     (("events", 10, "payload", "taskId"), 10),
                     (("events", 10, "payload", "success"), 1)]
        for path, value in mutations:
            with self.subTest(path=path, value=value):
                self.bad(changed(base, path, value))
        self.bad(changed(failure_retry(), ("events", 5, "payload", "resolution"), "NEW_COPY"))
        self.bad(changed(failure_retry(), ("events", 5, "payload", "source"), loc(1)))
        self.bad(changed(zeros(), ("events", 2, "payload", "copyOrdinal"), 1))

    def test_admission_and_replica_provenance_mutations(self):
        base = publication()
        p = ("events", 5, "payload")
        mutations = [(p + ("bytes",), 99), (p + ("bytes",), 0), (p + ("copyOrdinal",), 2),
                     (p + ("destinationVmId",), 3), (p + ("standaloneRate",), 11),
                     (p + ("isolatedSeconds",), 9), (p + ("sourceReplica", "visibleAt"), 2),
                     (p + ("sourceReplica", "origin", "observedAt"), 0),
                     (p + ("sourceReplica", "origin", "producerTaskId"), 11),
                     (p + ("sourceReplica", "origin", "jobAttemptId"), 101),
                     (p + ("sourceReplica", "acquisition"), "COPY_SETTLEMENT"),
                     (p + ("sourceReplica", "copiedFrom"), loc()),
                     (p + ("sourceReplica", "copyOrdinal"), 1),
                     (p + ("sourceReplica", "location"), loc(3))]
        for path, value in mutations:
            with self.subTest(path=path):
                self.bad(changed(base, path, value))
        self.bad(changed(fanin(), ("events", 16, "payload", "sourceReplica", "copiedFrom"), loc()))
        doc = prefix(publication(), 4)
        doc["events"].append(copy.deepcopy(publication()["events"][5]))
        self.bad(seal(doc))  # Orphan, even with a real source and valid route.

    def test_numeric_settlement_residual_bound_and_ulp_allowance(self):
        base = publication()
        for key, value in (("effectiveTime", 11), ("effectiveTime", 2), ("effectiveTime", 16),
                           ("remainingAfterService", -1), ("remainingAfterService", .01)):
            self.bad(changed(base, ("events", 7, "payload", key), value))
        # Scalar completion may stop just short of B; requiring B/rate would be wrong.
        doc = changed(base, ("events", 7, "payload", "remainingAfterService"), 1e-7)
        doc["events"][7]["payload"]["effectiveTime"] = 11.99999999
        self.assertEqual(1, audit(doc)["settlementCount"])
        # A one-ULP downward clock rounding passes, a large early finish does not.
        doc = changed(base, ("events", 7, "payload", "effectiveTime"), math.nextafter(12.0, 0.0))
        self.assertEqual(1, audit(doc)["settlementCount"])
        self.bad(changed(base, ("events", 7, "payload", "effectiveTime"), 12.0 - 1e-10))
        self.bad(changed(base, ("events", 7, "observedTime"), 2))

    def test_tiny_file_residual_half_cap_and_representable_clock(self):
        tiny = math.ulp(0.0)
        doc = publication()
        doc["filePlan"]["files"][0]["bytes"] = tiny
        doc["fabric"] = endpoints(((1, 1), (2, 1)))
        doc["events"][5]["payload"].update(bytes=tiny, standaloneRate=1, isolatedSeconds=tiny)
        self.bad(doc)  # Positive duration cannot advance the admission clock 2.
        # Finite but subnormal capacities are never supported V2 resources.
        self.bad(changed(publication(), ("fabric", "resources", 0, "capacityBytesPerSecond"), tiny))
        # Subnormal *files* are permitted when their positive duration advances
        # the clock. Here the half-B cap, not the relative term, controls residue.
        doc = publication()
        doc["fabric"] = endpoints(((1, 1), (2, 1)))
        doc["filePlan"]["files"][0]["bytes"] = 2 * tiny
        for row in doc["events"][:7]:
            row["observedTime"] = 0
        doc["events"][5]["payload"].update(bytes=2 * tiny, standaloneRate=1, isolatedSeconds=2 * tiny,
                                           sourceReplica=replica("data", 1, 0, "TASK_OUTPUT", 10, 100, 1, 0))
        doc["events"][7] = settle(1, tiny, 2 * tiny, tiny)
        for row in doc["events"][8:]:
            row["observedTime"] = 2 * tiny
        self.assertEqual(1, audit(seal(doc))["settlementCount"])
        self.bad(changed(doc, ("events", 7, "payload", "remainingAfterService"), 2 * tiny))

    def test_fat_tree_cross_pod_directional_literal_paths(self):
        doc = fat_document()
        self.assertEqual(CROSS_PATH, audit(doc)["facts"]["copies"][0]["resources"])
        reverse = publication()
        reverse["fabric"] = fat_fabric()
        reverse["events"][0]["payload"]["destinationVmId"] = 2
        for index in (2, 3):
            reverse["events"][index]["payload"]["vmId"] = 2
        reverse["events"][4]["payload"]["destinationVmId"] = 1
        reverse["events"][5]["payload"].update(sourceReplica=replica("data", 2, 1, "TASK_OUTPUT", 10, 100, 2, 1),
                                                destinationVmId=1, resources=list(REVERSE_PATH))
        reverse["events"][6]["payload"]["source"] = loc(2)
        for index in (9, 10):
            reverse["events"][index]["payload"]["vmId"] = 1
        self.assertEqual(REVERSE_PATH, audit(reverse)["facts"]["copies"][0]["resources"])
        self.bad(changed(doc, ("events", 5, "payload", "resources"), REVERSE_PATH))

    def test_fat_tree_same_host_edge_pod_and_reduced_core_literal_paths(self):
        cases = [
            (3, fat_fabric(), ["VM:1", "VM:3"], 30, 3.3333333333333335),
            (2, fat_fabric(4, 3, ((10, 0, 1), (20, 0, 1))),
             ["VM:1", "LINK:ACC:10->EDGE:0:1", "LINK:EDGE:0:1->ACC:20", "VM:2"], 10, 10),
            (2, fat_fabric(4, 3, ((10, 0, 1), (20, 0, 0))),
             ["VM:1", "LINK:ACC:10->EDGE:0:1", "LINK:EDGE:0:1->AGG:0:1",
              "LINK:AGG:0:1->EDGE:0:0", "LINK:EDGE:0:0->ACC:20", "VM:2"], 10, 10),
            (2, fat_fabric(4, 3, ((10, 0, 1), (20, 3, 0))),
             ["VM:1", "LINK:ACC:10->EDGE:0:1", "LINK:EDGE:0:1->AGG:0:1", "LINK:AGG:0:1->CORE:2",
              "LINK:CORE:2->AGG:3:1", "LINK:AGG:3:1->EDGE:3:0", "LINK:EDGE:3:0->ACC:20", "VM:2"], 10, 10),
            (2, fat_fabric(4, 4, ((10, 0, 1), (20, 2, 0))),
             ["VM:1", "LINK:ACC:10->EDGE:0:1", "LINK:EDGE:0:1->AGG:0:1", "LINK:AGG:0:1->CORE:3",
              "LINK:CORE:3->AGG:2:1", "LINK:AGG:2:1->EDGE:2:0", "LINK:EDGE:2:0->ACC:20", "VM:2"], 10, 10),
        ]
        for vm, fabric, path, rate, seconds in cases:
            doc = publication()
            doc["fabric"] = fabric
            doc["events"][4]["payload"]["destinationVmId"] = vm
            doc["events"][5]["payload"].update(destinationVmId=vm, resources=path, standaloneRate=rate, isolatedSeconds=seconds)
            for index in (9, 10):
                doc["events"][index]["payload"]["vmId"] = vm
            with self.subTest(path=path):
                self.assertEqual(path, audit(doc)["facts"]["copies"][0]["resources"])

    def test_source_is_off_fabric_and_vm_tie_precedes_source(self):
        source = replica("external", None, 0, "EXTERNAL_SEED")
        doc = document([task(0, inputs=[("external", 1)]), task(1, inputs=[("external", 1)])],
                       [file("external", 100)],
                       [seed("external"), request(0, 0, 2, 0), admit(1, "external", source, 2, 100, ["VM:2"], 40, 2.5, 0),
                        resolve(0, "external", "NEW_COPY", None, 0, 1), settle(1, 2.5, 3), ready(0, 3),
                        cpu(0, 2, 3), finish(0, 0, 2, 4)], fat_fabric())
        self.assertEqual(["VM:2"], audit(doc)["facts"]["copies"][0]["resources"])
        self.bad(changed(doc, ("events", 2, "payload", "resources"), ["SOURCE:source", "VM:2"]))
        # Endpoint-only tie: VM2's cached external object and SOURCE both offer 20 B/s.
        doc["fabric"] = endpoints(((1, 20), (2, 40)))
        cached = replica("external", 2, 3, "COPY_SETTLEMENT", copied_from=loc(), ordinal=1)
        doc["events"].extend([request(1, 1, 1, 4), admit(2, "external", cached, 1, 100, ["VM:2", "VM:1"], 20, 5, 4),
                              resolve(1, "external", "NEW_COPY", 2, 4, 2)])
        self.assertEqual(1, audit(seal(doc))["activeCopyCount"])
        doc["events"][-2]["payload"].update(sourceReplica=source, resources=["VM:1"])
        doc["events"][-1]["payload"]["source"] = loc()
        self.bad(doc)

    def test_topology_key_closure_capacity_and_safety_mutations(self):
        base = fat_document()
        mutations = [(("fabric", "topology", "k"), 34), (("fabric", "topology", "k"), 3),
                     (("fabric", "topology", "coreSwitchCount"), 2),
                     (("fabric", "topology", "linkBandwidthBytesPerSecond"), 11),
                     (("fabric", "topology", "hostPlacements", 0, "pod"), 2),
                     (("fabric", "topology", "hostPlacements", 0, "edge"), 1),
                     (("fabric", "topology", "hostPlacements", 1, "hostId"), 10),
                     (("fabric", "vmHostAssignments", 0, "hostId"), 99),
                     (("fabric", "vmHostAssignments", 0, "vmId"), 2),
                     (("fabric", "vmHostAssignments"), []),
                     (("fabric", "resources", 0, "capacityBytesPerSecond"), 0),
                     (("fabric", "resources", 0, "key"), "VM:01"),
                     (("fabric", "resources", 3, "capacityBytesPerSecond"), 11)]
        for path, value in mutations:
            with self.subTest(path=path):
                self.bad(changed(base, path, value))
        for key in ("resources", "locations", "vmHostAssignments"):
            doc = copy.deepcopy(base)
            doc["fabric"][key].append(copy.deepcopy(doc["fabric"][key][0]))
            self.bad(doc)
        doc = copy.deepcopy(base)
        doc["fabric"]["resources"].pop()   # Even an unused reverse link must be declared.
        self.bad(doc)
        doc = publication()
        doc["fabric"]["resources"].append(dict(key="SOURCE:source", capacityBytesPerSecond=10))
        self.bad(doc)
        self.bad(changed(publication(), ("fabric", "vmHostAssignments"), [dict(vmId=1, hostId=10)]))
        self.bad(changed(base, ("fabric", "topology", "hostPlacements", 1, "pod"), 0))

    def test_typed_locations_and_path_order_are_exact(self):
        base = publication()
        for value in ("VM:1", dict(kind="VM", vmId=1), dict(kind="VM", vmId=1, sourceId="source"),
                      dict(kind="SOURCE", vmId=1, sourceId="source"), dict(kind="SOURCE", vmId=None, sourceId="VM:1"),
                      dict(kind="VM", vmId=INT_MAX + 1, sourceId=None)):
            self.bad(changed(base, ("fabric", "locations", 0), value))
        self.bad(changed(base, ("fabric", "locations"), [loc(1), loc(2), loc(3)]))
        for path in (["VM:2", "VM:1"], ["VM:1", "VM:1", "VM:2"], ["VM:2"], ["VM:1", "source", "VM:2"]):
            self.bad(changed(base, ("events", 5, "payload", "resources"), path))
        v1_order = [CROSS_PATH[0], CROSS_PATH[-1]] + CROSS_PATH[1:-1]
        self.bad(changed(fat_document(), ("events", 5, "payload", "resources"), v1_order))

    def test_caller_immutable_facts_detached_and_no_subprocess(self):
        parsed = decode_json(json.dumps(fanin()))
        before = copy.deepcopy(parsed)
        with mock.patch("subprocess.Popen", side_effect=AssertionError("no subprocess")) as popen, \
             mock.patch("os.system", side_effect=AssertionError("no shell")) as system:
            report = verify_document(parsed)
            popen.assert_not_called()
            system.assert_not_called()
        self.assertEqual(before, parsed)
        report["facts"]["copies"][0]["sourceReplica"]["fileId"]["name"] = "changed"
        report["facts"]["jobs"][0]["taskIds"].append(999)
        self.assertEqual(before, parsed)
        bad = changed(parsed, ("events", 16, "payload", "standaloneRate"), Decimal("999"))
        before_bad = copy.deepcopy(bad)
        self.bad(bad)
        self.assertEqual(before_bad, bad)
        json.dumps(report, allow_nan=False)  # Summary has no Decimal, sets, dataclasses or live aliases.

    def test_inspect_path_is_strict_standalone_utf8_only(self):
        with mock.patch.object(Path, "read_text", return_value=json.dumps(publication())) as read:
            self.assertEqual("VALID_COMPLETE", inspect_path("hand-lifecycle.json")["status"])
            read.assert_called_once_with(encoding="utf-8")
        with mock.patch.object(Path, "read_text", side_effect=OSError("missing")):
            with self.assertRaises(Invalid):
                inspect_path("missing.json")
        for text in ('{"schema":"workflowsim-experiment-manifest-v4"}', '{"schema":1,"schema":2}'):
            with mock.patch.object(Path, "read_text", return_value=text), self.assertRaises(ValueError):
                inspect_path("invalid.json")


if __name__ == "__main__":
    unittest.main(verbosity=2)
